enum mainActionTypes {
  UPLOAD_FILE = 8678,
  PARSE_EXCEL_DATA,
  HANDLE_INPUT_CHANGE,
  UPDATE_ROW_COL_SIZE,
  SUBMIT_REPORT,
  DOWNLOAD_USER_DATA,
  SET_IS_RETURNING_USER_VALUE,
  PARSE_RETURNING_USER_EXCEL_DATA,
  UPLOAD_RETURNING_USER_FILE,
  SET_EMAIL,
  SET_PASSWORD,
  SET_ERROR_MESSAGE,
  LOGIN,
  CLEAR_RETURNING_USER_DATA
}

export default mainActionTypes;
